// Generated by tools/yarntoss_dev_data.py from the YarnToss repo - don't edit by hand.
window.GAME_DATA = {
 "achievements": [
  {
   "id": "tutorial_graduate",
   "name": "Tutorial Graduate",
   "description": "Finish the Tutorial",
   "type": "Progress",
   "stat": "tutorial_completed",
   "goal": 1,
   "enabled": true
  },
  {
   "id": "home_sweet_home",
   "name": "Home Sweet Home",
   "description": "Clear the Living Room",
   "type": "Progress",
   "stat": "rooms_cleared",
   "goal": 1,
   "enabled": true
  },
  {
   "id": "grand_tour",
   "name": "Grand Tour",
   "description": "Finish day 1",
   "type": "Progress",
   "stat": "laps_finished",
   "goal": 1,
   "enabled": true
  },
  {
   "id": "second_helping",
   "name": "Second Helping",
   "description": "Finish day 2",
   "type": "Progress",
   "stat": "laps_finished",
   "goal": 2,
   "enabled": true
  },
  {
   "id": "another_one",
   "name": "Another One",
   "description": "Finish day 3",
   "type": "Progress",
   "stat": "laps_finished",
   "goal": 3,
   "enabled": true
  },
  {
   "id": "ranked_debut",
   "name": "Ranked Debut",
   "description": "Finish day 1 in Ranked",
   "type": "Progress",
   "stat": "ranked_laps_finished",
   "goal": 1,
   "enabled": false
  },
  {
   "id": "all_nine_lives",
   "name": "All Nine Lives",
   "description": "Finish a Ranked day without losing a life",
   "type": "Skill",
   "stat": "ranked_flawless_laps",
   "goal": 1,
   "enabled": false
  },
  {
   "id": "meet_the_family",
   "name": "Meet the Family",
   "description": "Beat all 8 bosses",
   "type": "Boss",
   "stat": "bosses_beaten",
   "goal": 8,
   "enabled": false
  },
  {
   "id": "flawless",
   "name": "Flawless",
   "description": "Clear a room without losing health",
   "type": "Boss",
   "stat": "flawless_rooms",
   "goal": 1,
   "enabled": true
  },
  {
   "id": "flawless_tour",
   "name": "Flawless Tour",
   "description": "Get Flawless in all 8 rooms",
   "type": "Boss",
   "stat": "flawless_room_ids",
   "goal": 8,
   "enabled": false
  },
  {
   "id": "pan_master",
   "name": "Pan Master",
   "description": "Block 10 attacks with the Frying Pan in one boss fight",
   "type": "Boss",
   "stat": "pan_blocks_in_fight",
   "goal": 10,
   "enabled": true
  },
  {
   "id": "comeback_kid",
   "name": "Comeback Kid",
   "description": "Beat a boss with under 10% health left",
   "type": "Hidden",
   "stat": "boss_win_low_health",
   "goal": 90,
   "enabled": true
  },
  {
   "id": "on_a_roll",
   "name": "On a Roll",
   "description": "30 kills in a row without losing health",
   "type": "Skill",
   "stat": "kill_streak",
   "goal": 30,
   "enabled": true
  },
  {
   "id": "untouchable",
   "name": "Untouchable",
   "description": "60 kills in a row without losing health",
   "type": "Skill",
   "stat": "kill_streak",
   "goal": 60,
   "enabled": true
  },
  {
   "id": "cat_astrophe",
   "name": "Cat-astrophe",
   "description": "Take out 6 cats in one burst",
   "type": "Skill",
   "stat": "kill_burst",
   "goal": 6,
   "enabled": false
  },
  {
   "id": "close_shave",
   "name": "Close Shave",
   "description": "5 close calls in one run",
   "type": "Skill",
   "stat": "close_calls_in_run",
   "goal": 5,
   "enabled": false
  },
  {
   "id": "catnip_combo",
   "name": "Catnip Combo",
   "description": "Catch 5 cats with one catnip ring",
   "type": "Skill",
   "stat": "catnip_catch",
   "goal": 5,
   "enabled": true
  },
  {
   "id": "clean_sweep",
   "name": "Clean Sweep",
   "description": "Hit 8 cats with one Broomstick sweep",
   "type": "Playstyle",
   "stat": "broom_hits",
   "goal": 8,
   "enabled": true
  },
  {
   "id": "weapon_rack",
   "name": "Weapon Rack",
   "description": "Use every weapon: Yarn, Slipper and Hard Candy",
   "type": "Playstyle",
   "stat": "weapons_used",
   "goal": 3,
   "enabled": false
  },
  {
   "id": "collector",
   "name": "Collector",
   "description": "Buy every skill: Alarm Clock, Broomstick and Knitting Needles",
   "type": "Playstyle",
   "stat": "skills_bought",
   "goal": 3,
   "enabled": true
  },
  {
   "id": "fully_loaded",
   "name": "Fully Loaded",
   "description": "Max out any upgrade in a run",
   "type": "Playstyle",
   "stat": "upgrades_maxed",
   "goal": 1,
   "enabled": true
  },
  {
   "id": "big_spender",
   "name": "Big Spender",
   "description": "Spend 5,000 gold in one run",
   "type": "Playstyle",
   "stat": "gold_spent_in_run",
   "goal": 5000,
   "enabled": true
  },
  {
   "id": "fashionista",
   "name": "Fashionista",
   "description": "Wear a skin other than the default",
   "type": "Playstyle",
   "stat": "skins_equipped",
   "goal": 1,
   "enabled": true
  },
  {
   "id": "cat_person",
   "name": "Cat Person",
   "description": "Tap the main menu cat 20 times",
   "type": "Hidden",
   "stat": "menu_cat_taps",
   "goal": 20,
   "enabled": true
  },
  {
   "id": "community",
   "name": "Community",
   "description": "Visit the YarnToss Discord",
   "type": "Hidden",
   "stat": "discord_opened",
   "goal": 1,
   "enabled": true
  },
  {
   "id": "logger",
   "name": "Logger",
   "description": "Meet every cat in the Cat-alogue",
   "type": "Progress",
   "stat": "catalogue_found",
   "goal": 21,
   "enabled": true
  }
 ],
 "catalogue": [
  {
   "id": "cat_tier1",
   "name": "Stray Cat",
   "section": "Cats"
  },
  {
   "id": "cat_tier2",
   "name": "Page Cat",
   "section": "Cats"
  },
  {
   "id": "cat_tier3",
   "name": "Squire Cat",
   "section": "Cats"
  },
  {
   "id": "cat_tier4",
   "name": "Sword Cat",
   "section": "Cats"
  },
  {
   "id": "cat_tier5",
   "name": "Knight Cat",
   "section": "Cats"
  },
  {
   "id": "cat_tier6",
   "name": "Paladin Cat",
   "section": "Cats"
  },
  {
   "id": "cat_tier7",
   "name": "Captain Cat",
   "section": "Cats"
  },
  {
   "id": "cat_tier8",
   "name": "Dark Knight Cat",
   "section": "Cats"
  },
  {
   "id": "swarm_cat",
   "name": "Swarm Cat",
   "section": "Special cats"
  },
  {
   "id": "tank_cat",
   "name": "Tank Cat",
   "section": "Special cats"
  },
  {
   "id": "box_cat",
   "name": "Box Cat",
   "section": "Special cats"
  },
  {
   "id": "yawn_cat",
   "name": "Yawn Cat",
   "section": "Special cats"
  },
  {
   "id": "racket_cat",
   "name": "Racket Cat",
   "section": "Special cats"
  },
  {
   "id": "sir_fluffington",
   "name": "Sir Fluffington",
   "section": "Bosses"
  },
  {
   "id": "whisker",
   "name": "Whisker the Counter Raider",
   "section": "Bosses"
  },
  {
   "id": "grease_monkey",
   "name": "Grease Monkey",
   "section": "Bosses"
  },
  {
   "id": "squirrel_chaser",
   "name": "Squirrel-Chaser Max",
   "section": "Bosses"
  },
  {
   "id": "mommy_cat",
   "name": "Mommy Cat",
   "section": "Bosses"
  },
  {
   "id": "drainpipe_demon",
   "name": "Drainpipe Demon",
   "section": "Bosses"
  },
  {
   "id": "basement_beast",
   "name": "The Basement Beast",
   "section": "Bosses"
  },
  {
   "id": "alpha_cat",
   "name": "The Alpha Cat",
   "section": "Bosses"
  }
 ],
 "skins": [
  {
   "id": "granny_default",
   "name": "Granny",
   "product_id": ""
  },
  {
   "id": "mage",
   "name": "Mage Granny",
   "product_id": "skin_mage"
  },
  {
   "id": "biker",
   "name": "Biker Granny",
   "product_id": ""
  },
  {
   "id": "holiday",
   "name": "Holiday Granny",
   "product_id": ""
  },
  {
   "id": "beach",
   "name": "Beach Granny",
   "product_id": ""
  },
  {
   "id": "chef",
   "name": "Chef Granny",
   "product_id": "skin_chef"
  },
  {
   "id": "astro",
   "name": "Astro Granny",
   "product_id": "skin_astro"
  },
  {
   "id": "detective",
   "name": "Detective Granny",
   "product_id": "skin_detective"
  },
  {
   "id": "scuba",
   "name": "Scuba Granny",
   "product_id": "skin_scuba"
  },
  {
   "id": "supporter",
   "name": "Supporter Granny",
   "product_id": ""
  }
 ],
 "cosmetics": [
  {
   "id": "pop_bubbles",
   "name": "Bubbles",
   "kind": "hit_effect"
  },
  {
   "id": "pop_classic",
   "name": "Classic Pop",
   "kind": "hit_effect"
  },
  {
   "id": "pop_confetti",
   "name": "Confetti",
   "kind": "hit_effect"
  },
  {
   "id": "pop_cookies",
   "name": "Cookies",
   "kind": "hit_effect"
  },
  {
   "id": "pop_hearts",
   "name": "Hearts",
   "kind": "hit_effect"
  },
  {
   "id": "pop_paws",
   "name": "Paw Prints",
   "kind": "hit_effect"
  },
  {
   "id": "pop_stars",
   "name": "Stars",
   "kind": "hit_effect"
  },
  {
   "id": "yarn_berry",
   "name": "Berry Yarn",
   "kind": "yarn"
  },
  {
   "id": "yarn_classic",
   "name": "Classic Yarn",
   "kind": "yarn"
  },
  {
   "id": "yarn_midnight",
   "name": "Midnight Yarn",
   "kind": "yarn"
  },
  {
   "id": "yarn_mint",
   "name": "Mint Yarn",
   "kind": "yarn"
  },
  {
   "id": "yarn_sunset",
   "name": "Sunset Yarn",
   "kind": "yarn"
  }
 ],
 "workshop": [
  {
   "id": "early_pick",
   "name": "Early Bird",
   "description": "Start every run with free draft picks",
   "kind": "Perk",
   "max_level": 3
  },
  {
   "id": "free_reroll",
   "name": "Lucky Dice",
   "description": "Free draft rerolls each run, used before paid ones",
   "kind": "Perk",
   "max_level": 3
  },
  {
   "id": "kit_alarm_clock",
   "name": "Kit: Alarm Clock",
   "description": "Start a run already owning the Alarm Clock",
   "kind": "Kit",
   "max_level": 1
  },
  {
   "id": "kit_broomstick",
   "name": "Kit: Broomstick",
   "description": "Start a run already owning the Broomstick",
   "kind": "Kit",
   "max_level": 1
  },
  {
   "id": "kit_frosty_yarn",
   "name": "Kit: Frosty Yarn",
   "description": "Start a run already owning Frosty Yarn",
   "kind": "Kit",
   "max_level": 1
  },
  {
   "id": "kit_frying_pan",
   "name": "Kit: Frying Pan",
   "description": "Start a run already owning the Frying Pan",
   "kind": "Kit",
   "max_level": 1
  },
  {
   "id": "kit_piercing_yarn",
   "name": "Kit: Piercing Yarn",
   "description": "Start a run already owning Piercing Yarn",
   "kind": "Kit",
   "max_level": 1
  },
  {
   "id": "kit_shield",
   "name": "Kit: Shield",
   "description": "Start a run already owning the Shield",
   "kind": "Kit",
   "max_level": 1
  },
  {
   "id": "lucky_hand",
   "name": "Lucky Hand",
   "description": "Every draft hand deals 4 cards instead of 3",
   "kind": "Perk",
   "max_level": 1
  },
  {
   "id": "piggy_bank",
   "name": "Piggy Bank",
   "description": "Bank 2.5% more of the gold you earn as Savings, per level",
   "kind": "Perk",
   "max_level": 3
  }
 ],
 "rooms": [
  "Living Room",
  "Kitchen",
  "Garage",
  "Yard",
  "Bedroom",
  "Bathroom",
  "Basement",
  "Attic"
 ],
 "products": [
  "supporter_pack",
  "starter_pack",
  "wardrobe_bundle",
  "skin_mage",
  "skin_chef",
  "skin_astro",
  "skin_detective",
  "skin_scuba"
 ]
};
