"""Regenerates dev/yarntoss/game-data.js from a YarnToss checkout.

The dev panel shows ids from a player's save (achievements, Cat Catalogue
entries, skins, cosmetics, Workshop upgrades) with their real names. Those
names live in the game's data files, so this copies them over. Run it after
adding or renaming any of those in the game:

    python tools/yarntoss_dev_data.py ../YarnToss

Only reads the game repo. Unknown ids still show in the panel, just raw.
"""

import csv
import json
import re
import sys
from pathlib import Path


def tres_fields(path: Path) -> dict:
    """The simple `key = value` lines of a .tres [resource] section."""
    fields = {}
    in_resource = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("["):
            in_resource = line.startswith("[resource")
            continue
        if not in_resource:
            continue
        m = re.match(r'^(\w+) = (.+)$', line)
        if not m:
            continue
        key, raw = m.groups()
        if raw.startswith('"') and raw.endswith('"'):
            fields[key] = json.loads(raw)
        elif re.fullmatch(r"-?\d+", raw):
            fields[key] = int(raw)
        elif raw.startswith("Array[int]("):
            fields[key] = [int(x) for x in re.findall(r"-?\d+", raw[len("Array[int]("):])]
    return fields


def preload_order(script: Path, folder: str) -> list:
    """Resource paths in the order a registry script preloads them."""
    text = script.read_text(encoding="utf-8")
    return re.findall(r'preload\("res://(resources/%s/[\w]+\.tres)"\)' % folder, text)


def main() -> None:
    game = Path(sys.argv[1] if len(sys.argv) > 1 else "../YarnToss").resolve()
    out = Path(__file__).resolve().parent.parent / "dev" / "yarntoss" / "game-data.js"

    achievements = []
    with open(game / "data" / "achievements.csv", encoding="utf-8") as f:
        rows = [line for line in f if not line.startswith("#")]
    for row in csv.DictReader(rows):
        achievements.append({
            "id": row["id"], "name": row["name"], "description": row["description"],
            "type": row["type"], "stat": row["stat"], "goal": int(row["goal"] or 0),
            "enabled": row["enabled"].strip().lower() == "yes",
        })

    sections = ["Cats", "Special cats", "Bosses"]
    catalogue = []
    for rel in preload_order(game / "scripts" / "cat_catalogue.gd", "catalogue"):
        f = tres_fields(game / rel)
        catalogue.append({"id": f["id"], "name": f.get("display_name", f["id"]),
                          "section": sections[f.get("section", 0)]})

    skins = []
    for rel in preload_order(game / "scripts" / "skin_registry.gd", "skins"):
        f = tres_fields(game / rel)
        skins.append({"id": f["id"], "name": f.get("display_name", f["id"]),
                      "product_id": f.get("product_id", "")})

    cosmetic_kinds = ["yarn", "hit_effect"]
    cosmetics = []
    for path in sorted((game / "resources" / "cosmetics").glob("*.tres")):
        f = tres_fields(path)
        cosmetics.append({"id": f["id"], "name": f.get("display_name", f["id"]),
                          "kind": cosmetic_kinds[f.get("kind", 0)]})

    meta_kinds = ["Perk", "Kit"]
    workshop = []
    for path in sorted((game / "resources" / "meta_upgrades").glob("*.tres")):
        f = tres_fields(path)
        workshop.append({"id": f["id"], "name": f.get("display_name", f["id"]),
                         "description": f.get("description", ""),
                         "kind": meta_kinds[f.get("kind", 0)], "max_level": f.get("max_level", 1)})

    rooms = []
    for rel in preload_order(game / "scripts" / "level_registry.gd", "levels"):
        f = tres_fields(game / rel)
        rooms.append(f.get("display_name", f.get("id", "?")))

    store = (game / "scripts" / "store_catalog.gd").read_text(encoding="utf-8")
    products = re.findall(r'^const \w+_(?:PACK|BUNDLE): String = "(\w+)"', store, re.M)
    products += [s["product_id"] for s in skins if s["product_id"]]

    data = {
        "achievements": achievements, "catalogue": catalogue, "skins": skins,
        "cosmetics": cosmetics, "workshop": workshop, "rooms": rooms, "products": products,
    }
    out.write_text(
        "// Generated by tools/yarntoss_dev_data.py from the YarnToss repo - don't edit by hand.\n"
        "window.GAME_DATA = " + json.dumps(data, indent=1, ensure_ascii=False) + ";\n",
        encoding="utf-8", newline="\n")
    print(f"Wrote {out} ({len(achievements)} achievements, {len(catalogue)} catalogue, "
          f"{len(skins)} skins, {len(cosmetics)} cosmetics, {len(workshop)} workshop, {len(rooms)} rooms)")


if __name__ == "__main__":
    main()
